# Generated by Django 2.2.13 on 2020-06-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
