# Generated by Django 2.2.13 on 2020-06-14 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electro', '0002_auto_20200613_2145'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suggestion',
        ),
    ]
