# Generated by Django 2.2.13 on 2020-06-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('electro', '0003_delete_suggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(default='99999999', max_length=8)),
                ('telephone2', models.CharField(default='99999999', max_length=8)),
                ('email', models.CharField(default='electro@email.com', max_length=50)),
                ('address', models.CharField(default='17 Princess Road, London, Greater London NW1 8JR, UK', max_length=255)),
                ('date_cre', models.DateTimeField(auto_now_add=True)),
                ('date_mod', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Info',
                'verbose_name_plural': 'Infos',
            },
        ),
    ]
