# Generated by Django 2.2.13 on 2020-06-13 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(related_name='categorieArticle', to='blog.BlogCategory'),
        ),
    ]
